name: Daily Headline News

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create firebase key file
        run: echo '${{ secrets.FIREBASE_ADMIN_KEY }}' > serviceAccountKey.json

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py